### ISSUE TITLE
prometheus got error cannot list resource \"services\" in API group \"\" in the namespace \"xxxx\"

### ISSUE THREAD

**Issue by hanyouqing** [AliyunContainerService/prometheus-operator#1]
prometheus-k8s should be ClusterRole with verbs: ["get", "watch", "list"].

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: prometheus-k8s
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: prometheus-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
```
