### ISSUE TITLE
Alertmanager is recommended to integrate common alarm configurations by default.

### ISSUE THREAD

**Issue by hanyouqing** [AliyunContainerService/prometheus-operator#4]
```yaml
# @reference:
#     https://github.com/prometheus/alertmanager
#     https://prometheus.io/docs/alerting/configuration/
#     https://help.aliyun.com/document_detail/29449.html
global: 
  resolve_timeout: '5m'
  smtp_hello: 'aliyun.com'
  smtp_from: 'monit@inc.teachmyself.cn'
  smtp_smarthost: 'smtpdm.aliyun.com:80'
  smtp_auth_username: 'monit@inc.teachmyself.cn'
  smtp_auth_password: 'password'
  smtp_require_tls: false
  # smtp_auth_identity: ''
  # smtp_auth_secret: ''

route: 
  group_by: 
  - 'alertname'
  - 'cluster'
  - 'job'
  - 'severity'
  group_wait: '30s'
  group_interval: '5m'
  repeat_interval: '6h'
  receiver: 'default'
  routes: 
  - receiver: 'email'
  - match: 
      alertname: 'CoreDNSDown'
    receiver: null

receivers: 
- name: 'default'
  email_configs: 
  - to: 'monit@inc.teachmyself.cn'
    send_resolved: true
- name: 'email'
  email_configs:
  - to: 'me@teachmyself.cn'
    send_resolved: true
```
