### ISSUE TITLE
Integration of common middleware is recommended, such as mysql, redis, kafka.

### ISSUE THREAD

**Issue by hanyouqing** [AliyunContainerService/prometheus-operator#5]
```yaml
# @reference:
#   https://developer.rackspace.com/docs/rkaas/v1.5.x/external/rkaas-userguide/rkaas-logging-mon/deploy-kubernetes-application/
#   kubectl port-forward svc/mysqld-exporter 9104
---
apiVersion: v1
data:
  DATA_SOURCE_NAME: ZGJ1c2VyOmRibmFtZUAoZGJob3N0OmRicG9ydCkvcGVyZm9ybWFuY2Vfc2NoZW1hCg==
kind: Secret
metadata:
  name: mysql-exportor-teachmyself
  namespace: monitoring
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  labels:
    app: mysqld-exporter
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9104
  selector:
    app: mysqld-exporter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysqld-exporter
  labels:
    app: mysqld-exporter
spec:
  selector:
    matchLabels:
      app: mysqld-exporter
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
      labels:
        app: mysqld-exporter
    spec:
      containers:
      - name: mysqld-exporter
        image: prom/mysqld-exporter
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              key: DATA_SOURCE_NAME
              name: mysql-exportor-teachmyself
        ports:
        - containerPort: 9104
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysqld-exporter
  namespace: monitoring
  labels:
    monitor-app: mysqld-exporter
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      app: mysqld-exporter
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http-metrics
    interval: 30s
```
